version: 2

# Circle jobs
jobs:

  # Verify code then run unit and integration tests
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run: make build
      - run: make verify
      - run: make test

  # deploy the navigation JSON
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run: make build
      - run: make deploy
      - run: make release-log || true
      - run: make update-cmdb
      - run: make auto-version

# Circle workflows
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
