version: 2.1

orbs:
    change-api: financial-times/change-api@0.24.0

jobs:

  # Verify code then run unit and integration tests
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run: make build
      - run: make verify
      - run: make test

  # deploy the navigation JSON
  deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run: make build
      - run: make deploy
      - run: make update-cmdb
      - run: make auto-version

# Circle workflows
workflows:
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
      - change-api/release-log:
          requires:
            - deploy
          systemCode: 'origami-navigation-service-data'
          environment: 'prod'
          slackChannels: 'origami-deploys'
          filters:
            branches:
              only:
                - master
